services:
  veilnet-conlux:
    build: .
    container_name: veilnet-conflux
    image: veilnet/conflux:latest
    pull_policy: always
    restart: unless-stopped
    privileged: true
    # network_mode: host
    # env_file:
    #   - .env
